# Generated by Django 4.2.20 on 2026-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robbo_certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedesign',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
